apiVersion: v1
kind: Pod
metadata:
  name: vol-test-pod
  labels:
    app: vol-test
spec:
  containers:
    - name: nginx-test
      image: nginx
      volumeMounts:
        - name : nginx-logs
          mountPath: /var/log/nginx
    - name: almalinux
      image: almalinux:9
      volumeMounts:
        - name: nginx-logs
          mountPath: /mnt/nginx-logs
          readOnly: true
      command: ["sleep", "2000"]
  volumes:
    - name: nginx-logs
      emptyDir:
        sizeLimit: 500Mi

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-logs-service
spec:
  type: NodePort
  selector:
    app: vol-test
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080






