apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-dynamic-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: roboshop-ebs-sc # This is the StorageClass name which we want to use in this PVC which creates PV dynamically
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: Pod
metadata:
  name: app
spec:
  nodeSelector:
    topology.kubernetes.io/zone: "us-east-1c" # This is the availability zone where EBS volume will be created
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: html-data # Name must be same as defined in volumes section
      mountPath: /usr/share/nginx/html # This is the path where we want to mount this volume
  volumes:
  - name: html-data # we can give any name to this volume
    persistentVolumeClaim:
      claimName: ebs-dynamic-claim  # This is PVC name which we want to use in this POD
