apiVersion: v1
kind: Pod
metadata:
  name: multi-container
spec:
  containers:
  - name: nginx-c
    image: nginx
    ports:
    - containerPort: 80
      hostPort: 80
  - name: almalinux
    image: almalinux:9
    command: ["sleep", "1000"]