apiVersion: v1
kind: Pod
metadata:
  name: env-test-nginx
spec:
  containers:
    - name: env-test-nginx
      image: nginx
      env:
        - name: project
          value: roboshop
        - name: environment
          value: development
        - name: topic
          value: kubernetes
