apiVersion: v1
kind: Secret
metadata:
  name: nginx-secrets
data:
  # By default, the values in a secret are stored as base64 encoded strings. So, we need to encode the values before adding them to the secret.
  username: c2Fp
  password: c2FpQDEyMw==