apiVersion: v1
kind: Secret
metadata:
  name: nginx-secrets
data:
  # By default, the values in a secret are stored as base64 encoded strings. So, we need to encode the values before adding them to the secret.
  username: c2Fp
  password: c2FpQDEyMw==

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-secrets-test
spec:
  containers:
  - name: nginx-secret-test
    image: nginx
    # Using envFrom to load all secrets as environment variables in the container
    envFrom:
    # Using secretRef to reference the nginx-secrets in the pod specification available with base64 decoded values as environment variables in the container.
    - secretRef:
        name: nginx-secrets   # Name of the secret to reference.
  