apiVersion: v1
kind: Pod
metadata:
  name: nginx-secrets-test
spec:
  containers:
  - name: nginx-secret-test
    image: nginx
    # Using envFrom to load all secrets as environment variables in the container
    envFrom:
    # Using secretRef to reference the nginx-secrets in the pod specification available with base64 decoded values as environment variables in the container.
    - secretRef:
        name: nginx-secrets   # Name of the secret to reference.
  