apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  # Default service type is ClusterIP, which is used for internal communication within the cluster even if we do not specify it.
  selector:
    # labels are used as selectors
    project: roboshop
    component: frontend
    environment: dev
  ports:
  - protocol: TCP
    port: 80 # This is the port on which the service will be exposed within the cluster.
    targetPort: 80 # Container port to which the traffic will be forwarded.