apiVersion: v1
kind: Service # Used for pod to pod communication within the cluster. It provides a stable IP address and DNS name for a set of pods, also load balances traffic across those pods.
metadata:
  name: nginx-service
spec:
  # Default is ClusterIP.
  selector: # labels are used as selector to identify the pods that this service will route traffic to. The service will forward traffic to any pod that has these labels.
    project: roboshop
    component: frontend
    environment: dev
  ports:
  - protocol: TCP
    port: 80 # This is the port on which the service will be exposed within the cluster.
    targetPort: 80 # Container port to which the traffic will be forwarded.